In [1]:
from numpy import set_printoptions
from sklearn.preprocessing import Binarizer
from pandas import read_csv
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class'] 
dataframe = read_csv(url, names=names)
array = dataframe.values
# seperate array into input & output components
X = array [:,0:8]
Y = array [:,8]
binarizer = Binarizer(threshold=0.0) .fit(X)
binaryX = binarizer.transform(X)
#summarize transformed data
set_printoptions(precision=4)
print(binaryX[0:5,:])

[[1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1.]]


In [2]:
# CH 7 OF PRE-PROCESSING DATA / LESSON SUMMARY 
# RESCALE DATA = FOR ALGOS LIKE GRADIENT DESCENT & OPTIMIZATION ALGOS + ALGOS THAT REQ REIGHT INPUTS LIKE REGRESSION, NEURAL NETWORKS, DISTANCE (K-NEAREST NEIGHBOR) 
#STANDARDIZE DATA = SOMETIMES LINEAR REGRESSIONS + LOGISTICAL ALGOS REQS  TRANSFORM DATA ATTRIBUTES W/ GAUSSIAN DISTRB AND DIFFERING MEANS/STD -> STANDARD GAUSSIAN DISTRIB W/ A MEAN OF 0 AND A STDDEV OF 1
#NORMALIZE DATA = This pre-processing method can be useful for sparse datasets (lots of zeros) with attributes of varying scales when using algorithms that weight input values such as neural networks and algorithms that use distance measures such as k-Nearest Neighbors.
 #BINARIZE DATA = TURN FUZZY NUMBERS INTO CRISP VALUES WHEN DOING FEATURE ENGINEERING AND U WANT TO ADD FEATURES THAT ARE MEANINGFUL